Dockerfile, examples/segment_pnh_kepkee.py, examples/test_denoise.py, macapype/nodes/register.py, macapype/pipelines/extract_brain.py, macapype/utils/utils_tests.py
=> Docker denoise

Dockerfile, README.md, examples/segment_from_mask_pnh_kepkee.py, examples/segment_pnh_kepkee.py, examples/segment_pnh_regis.py, macapype/nodes/tests/test_bash_regis.py, macapype/pipelines/preproc.py
Modif -cropped to -crop_req (add marker if cropping is required) + modified docker
=> [MRG] If no cropped box

macapype/pipelines/full_segment.py
=> Revert "changed pipeline name"

.travis.yml, doc/index.rst, doc/workflows.rst, examples/plot_segment_marmo_test.py, examples/plot_segment_pnh_isabelle.py, macapype/bash/NMT_subject_align.csh, macapype/bash/atlasBREX.sh, macapype/nodes/extract_brain.py, macapype/nodes/preproc.py, macapype/nodes/register.py, macapype/pipelines/extract_brain.py, macapype/pipelines/preproc.py, macapype/pipelines/register.py, macapype/utils/templates.json, macapype/utils/utils_tests.py, workflows/params_segment_marmo_test.json, workflows/params_segment_pnh_isabelle.json, workflows/segment_pnh_kepkee.py
A better version of https://github.com/Macatools/macapype/pull/30
=> Modif template access, and reorient sphinx and marmouset examples

macapype/pipelines/correct_bias.py, macapype/pipelines/full_pipelines.py, macapype/pipelines/prepare.py, macapype/pipelines/register.py, macapype/pipelines/segment.py, macapype/utils/tests/test_utils_nodes.py, macapype/utils/utils_nodes.py, run_examples/run_segment_pnh_kepkee.py, run_examples/run_segment_pnh_regis_T1xT2.py, workflows/params_segment_pnh_kepkee.json, workflows/params_segment_pnh_regis_T1xT2.json
added NodeParams instead of nodes for reading all params (from the json file) from a dict
Should ultimately be added upstream (in nipype) if required
=> Add node params

examples/plot_segment_marmo_test.py, examples/plot_segment_pnh_isabelle.py, examples/plot_segment_pnh_kepkee.py, examples/plot_segment_pnh_regis_T1xT2.py, macapype/utils/utils_tests.py, run_examples/run_segment_marmo_test.py, run_examples/run_segment_pnh_isabelle.py, run_examples/run_segment_pnh_kepkee.py, run_examples/run_segment_pnh_regis_T1xT2.py, workflows/segment_pnh_regis_T1xT2.py
added data_marmo_test and data_test_macapype_ziggy, so all examples are now from load_test_data, and no hard path are fixed, all is relative to the data_path
=> all examples are now without fixed paths

doc/index.rst, doc/workflows.rst, examples/plot_segment_marmo_ants_based.py, examples/plot_segment_pnh_ants_based.py, examples/plot_segment_pnh_spm_based.py, examples/plot_segment_sphinx_pnh_ants_based.py, macapype/bash/NMT_subject_align.csh, macapype/nodes/register.py, macapype/pipelines/prepare.py, macapype/pipelines/register.py, run_examples/run_segment_marmo_ants_based.py, run_examples/run_segment_pnh_ants_based.py, run_examples/run_segment_pnh_spm_based.py, run_examples/run_segment_sphinx_pnh_ants_based.py, workflows/params_segment_pnh_ants_based.json
deoblique from data preparation to register is working much better
=> [MRG] Modif doc and solved bug align (deoblique)

macapype/nodes/segment.py
Fix a call to a version of atroposN4.sh in the bash dir that does not exists
=> corrected atropos

macapype/pipelines/extract_brain.py, macapype/pipelines/full_pipelines.py, macapype/pipelines/prepare.py, macapype/utils/misc.py, macapype/utils/utils_bids.py, workflows/params_segment_pnh_ants_based_crop.json, workflows/segment_multi_pnh_ants_based.py
Invidual parameters of part of the pipeline are added under the key "macapype" in the BIDS sidecar of the T1w file; a better version could be done...
=> added all 'multi' files and function

workflows/segment_pnh_ants_based.py
my_path was set to a fixed path
=> [FIX] my_path was set to a fixed path by default

Dockerfile, doc/docker_install.rst
Tested build Dockerfile and Docker pull; made an alias for afni calling python3 when calling python
=> [MRG][BUG] Fix docker file

doc/contribute.rst, doc/index.rst, doc/install.rst
Added the [contribute page](https://macatools.github.io/macapype/contribute.html#contribute) of the documentation and added links to the main index page
=> [MRG][DOC]added contribute.rst and how to contribute to package

macapype/pipelines/full_pipelines.py, macapype/pipelines/prepare.py, macapype/pipelines/tests/test_full_pipelines.py, macapype/utils/templates.json, workflows/segment_pnh.py
I added a T1w only SPM based segmentation pipeline
=> Add T1 only spm pipeline

macapype/pipelines/full_pipelines.py, workflows/params_segment_macaque_spm_based_crop.json
added crop to the SPM (T1*T2) pipeline instead of the betcrop only possibility so far. the BET is now done at the debias level only
=> Modif spm crop

macapype/pipelines/segment.py
merge_indexed_mask was only done with prob =1.0 even if thresholded at 0.5;
now after bin, all operations are done on binarized data
=> Bin thresh merge

macapype/pipelines/full_pipelines.py, macapype/pipelines/prepare.py, workflows/segment_pnh.py
Added FLAIR with T1 only, and cleaned SPM T1
Also added mesh_fs in ANTS_T1
=> Modif t1 pipelines

workflows/segment_pnh.py
did not work when regex_subs was not in params (should not be made mandatory)
=> BUG: test if regex_subs in params

macapype/nodes/extract_brain.py, macapype/pipelines/register.py
NMT_subject_align was not reading params (in particular the previous modifications in afni_ext)
=> hotfix_NMT_subject_align

macapype/pipelines/full_pipelines.py, workflows/segment_pnh.py
+ correction ANTS_T1 and ANTS_T1 template
=> Merge spm template native

macapype/nodes/register.py, macapype/nodes/segment.py, macapype/pipelines/full_pipelines.py, macapype/pipelines/register.py, macapype/pipelines/segment.py, workflows/params_segment_baboon_ants.json, workflows/params_segment_baboon_ants_t1.json, workflows/params_segment_baboon_ants_t1t2debias.json, workflows/params_segment_chimp_ants_t1.json, workflows/params_segment_macaque_ants.json, workflows/params_segment_macaque_ants_segkmeans.json, workflows/params_segment_macaque_ants_t1.json, workflows/params_segment_macaque_ants_t1t2debias.json, workflows/params_segment_macaque_ants_template.json, workflows/params_segment_macaque_spm.json, workflows/params_segment_marmo_ants.json, workflows/params_segment_marmo_ants_t1.json, workflows/params_segment_marmo_ants_t1t2debias.json
Correction with segmentation priors (previously the segmentation was done with k-means only)
=> Hotfix seg at

.github/workflows/ci.yml, macapype/nodes/segment.py, macapype/nodes/tests/test_segment.py, macapype/pipelines/full_pipelines.py, macapype/pipelines/prepare.py, macapype/pipelines/register.py, macapype/pipelines/segment.py, macapype/utils/tests/test_misc.py, workflows/segment_pnh.py
testing if github actions are working properly
=> Test GitHub actions

workflows/params_segment_baboon_ants.json, workflows/segment_pnh.py
depending on whether -indiv is set, and what is in indiv_params.json,… different preparation are set
=> [ENH] test no indiv and indiv_params content

.github/workflows/build_on_release.yml
Same as PR https://github.com/Macatools/macapype/pull/172 (but the error was also in the build_on_release file)
=> added marmo-marmobrain/ to build_on_release as well

workflows/segment_pnh.py
all derivatives after testing were going in the same directory...
=> wf_name used now for naming of derivatives

Dockerfile_spm_mcr, workflows/segment_pnh.py
change long_single and long_multi in wf_name and derivs to differentiate test baboon indiv
=> Name long prep

TODO.txt, macapype/nodes/prepare.py, macapype/pipelines/full_pipelines.py, macapype/pipelines/register.py, macapype/utils/data_test_servers.json, workflows/params_segment_baboon_ants.json, workflows/params_segment_chimp_ants.json, workflows/params_segment_macaque_ants.json, workflows/params_segment_marmo_ants.json, workflows/segment_pnh.py
Added possiblity of adding template by user (instead of being defined in params.json as "template_name" in "general")
Now in the CLI:
-> -template path 
-> -template names, should contains either 3 or 5 files
=> Add user template

macapype/nodes/prepare.py, macapype/pipelines/segment.py, workflows/segment_pnh.py
Padding with original dtype 
(default values have  still to be worked on)
=> Modif padding

macapype/pipelines/full_pipelines.py, macapype/pipelines/segment.py, macapype/utils/subs.json, workflows/params_segment_marmo_ants.json, workflows/segment_pnh.py
spm pad and deriv were not implemented yet
=> Hotfix spm pad

macapype/pipelines/full_pipelines.py
Related to issue https://github.com/Macatools/macapype/issues/205
=> Pad long single (ANTS and SPM)

macapype/_version.py, macapype/pipelines/full_pipelines.py, macapype/pipelines/prepare.py, macapype/utils/misc.py
0.3.2-fix3
No more orig 
-> added align T2 on T1 as first step, and always apply reg_resample and crop to t2
-> big bug (the reg_aladin for ants_T1 was taking inia19 as expected for macaque
=> Merge crop z t2

macapype/nodes/surface.py, macapype/pipelines/full_pipelines.py, macapype/pipelines/surface.py, workflows/segment_pnh.py
added new mesh2nii pipeline from wm and gm; removed skull_petra pipeline after test in new project PNH_IRMTo3D
=> Nii2mesh petra pipe

workflows/params_segment_macaque_spm.json
inia was not padded correctly either...
=> "NMT_v2.0_asym" for template stereo name (inia not in stereo space)

macapype/pipelines/full_pipelines.py, macapype/pipelines/prepare.py, macapype/pipelines/rename.py, macapype/pipelines/segment.py, macapype/utils/utils_params.py
Bug : the native_T2 was really the native_T1, and everything following
Bug: there was an issue with indiv_params if no ses was given (as the CENIR dataset)
=> Hotfix native t2

Dockerfile, macapype/utils/utils_params.py, workflows/params_segment_baboon_ants.json, workflows/params_segment_baboon_spm.json, workflows/params_segment_macaque_ants.json, workflows/params_segment_macaque_spm.json, workflows/params_segment_marmo_ants.json, workflows/params_segment_marmo_spm.json, workflows/segment_pnh.py
Modified all params for only one reg_t1_to_template by default, and adding _robustreg in soft will add the 2 magical parameters of reg_aladin
=> Robustreg option

macapype/pipelines/full_pipelines.py, macapype/utils/subs.json, setup.py, workflows/segment_pnh.py
Added full_command (macapype version was already thre it seems..) + solved some bugs
=> Modif real params

setup.py
package skullTo3d brings an error with numpy / Cython
https://github.com/Macatools/skullTo3d/actions/runs/9547727415/job/26313351754
=> test if working with newest version of numpy

examples_doc/params_general_preparation.json, macapype/pipelines/prepare.py
reg_aladin between T2 and T1 must be with options rigidOnly
=> added rigid_flag

docs/docker_install.rst, docs/index.rst, docs/quick_install.rst, docs/quick_test.rst, macapype/pipelines/full_pipelines.py
=> Hotfix registe to nat haiko

docs/docker_install.rst, docs/index.rst, docs/quick_install.rst, docs/quick_test.rst, macapype/nodes/extract_brain.py, macapype/nodes/surface.py, macapype/pipelines/surface.py, macapype/utils/utils_params.py
=> Add quick test to doc

macapype/nodes/pad.py, macapype/pipelines/full_pipelines.py, macapype/pipelines/rename.py
pad_back denoised to native space
=> Native denoised + removed useless inputnode in pad_back

macapype/pipelines/full_pipelines.py, macapype/pipelines/rename.py, macapype/pipelines/surface.py
Each separated tissue (GM/WM/CSF) is exported as a a surface mesh (so far only used in skullTo3d workflows)
=> [ENH] stl by seg tissue
